[project]
name = "epwshiftr"
r_version = "=4.6.1"

[dependencies]
checkmate = ">=2.0.0"
cli = ">=3.4.0"
curl = "*"
"data.table" = ">=1.12.4"
duckdb = "*"
jsonlite = "*"
mirai = "2.7.3"
nanonext = "1.10.3"
R6 = "*"
RNetCDF = "*"
S7 = "*"
testthat = ">=3.0.0"
webfakes = "*"
withr = "*"
callr = "*"
pkgload = "*"
rcmdcheck = "*"
roxygen2 = "8.1.0"
processx = "*"
ps = "*"
