# install_cli() and uninstall_cli() {{{
test_that("install_cli() / uninstall_cli() manage generated launchers", {
    bin_dir <- tempfile("epwshiftr-bin-")
    name <- "epwshiftr-test"
    installed <- install_cli(bin_dir = bin_dir, name = name)
    expect_true(file.exists(installed$path))
    expect_equal(installed$bin_dir, normalizePath(bin_dir, mustWork = FALSE, winslash = "/"))
    expect_false(installed$in_path)

    content <- readLines(installed$path, warn = FALSE)
    expect_true(any(grepl("Generated by epwshiftr::install_cli\\(\\)", content)))
    expect_true(any(grepl("epwshiftr::epwshiftr_cli\\(exit = TRUE\\)", content)))
    expect_error(install_cli(bin_dir = bin_dir, name = name), "already exists")
    overwritten <- install_cli(bin_dir = bin_dir, name = name, overwrite = TRUE)
    expect_equal(overwritten$path, installed$path)
    if (.Platform$OS.type != "windows") {
        expect_equal(unname(file.access(installed$path, 1L)), 0L)
    }

    removed <- uninstall_cli(bin_dir = bin_dir, name = name)
    expect_true(removed$removed)
    expect_false(file.exists(installed$path))

    dir.create(bin_dir, recursive = TRUE, showWarnings = FALSE)
    unsafe <- file.path(bin_dir, if (.Platform$OS.type == "windows") paste0(name, ".cmd") else name)
    writeLines("not generated by epwshiftr", unsafe)
    expect_error(uninstall_cli(bin_dir = bin_dir, name = name), "Refusing to remove")
    expect_true(file.exists(unsafe))
})
# }}}
