#' Install the epwshiftr command launcher
#'
#' @description
#' `install_cli()` writes a small platform launcher that runs the current
#' `Rscript` with `epwshiftr::epwshiftr_cli(exit = TRUE)`. It does not modify
#' shell profiles or `PATH`.
#'
#' @param bin_dir Directory where the launcher should be written. Defaults to
#'        `~/.local/bin` on macOS/Linux and
#'        `%LOCALAPPDATA%/epwshiftr/bin` on Windows.
#' @param name Launcher command name. Default: `"epwshiftr"`.
#' @param overwrite Whether to replace an existing launcher. Default: `FALSE`.
#'
#' @return A data.table describing the installed launcher.
#' @export
install_cli <- function(bin_dir = NULL, name = "epwshiftr", overwrite = FALSE) {
    checkmate::assert_string(bin_dir, min.chars = 1L, null.ok = TRUE)
    checkmate::assert_string(name, min.chars = 1L)
    checkmate::assert_flag(overwrite)
    if (!grepl("^[A-Za-z][A-Za-z0-9._-]*$", name)) {
        cli::cli_abort("{.arg name} must start with a letter and contain only letters, digits, '.', '_', or '-'.")
    }

    spec <- epwshiftr_cli_launcher_spec(bin_dir, name)
    if (file.exists(spec$path) && !isTRUE(overwrite)) {
        cli::cli_abort("Launcher already exists at {.path {spec$path}}. Use {.code overwrite = TRUE} to replace it.")
    }
    if (!dir.exists(spec$bin_dir)) {
        dir.create(spec$bin_dir, recursive = TRUE, showWarnings = FALSE)
    }
    if (!dir.exists(spec$bin_dir)) {
        cli::cli_abort("Failed to create launcher directory: {.path {spec$bin_dir}}.")
    }
    spec$bin_dir <- normalizePath(spec$bin_dir, mustWork = TRUE, winslash = "/")
    spec$path <- file.path(spec$bin_dir, basename(spec$path))

    writeLines(epwshiftr_cli_launcher_content(spec$windows), spec$path, useBytes = TRUE)
    if (!isTRUE(spec$windows)) {
        Sys.chmod(spec$path, mode = "0755")
    }
    in_path <- epwshiftr_cli_bin_in_path(spec$bin_dir)
    if (!isTRUE(in_path)) {
        cli::cli_inform("Launcher installed at {.path {spec$path}}, but {.path {spec$bin_dir}} is not currently on PATH.")
    }
    data.table::data.table(
        path = spec$path,
        bin_dir = spec$bin_dir,
        command = spec$command,
        in_path = in_path,
        installed = TRUE
    )
}


#' Uninstall the epwshiftr command launcher
#'
#' @description
#' Remove a launcher generated by `install_cli()`.
#'
#' @inheritParams install_cli
#'
#' @return A data.table describing the uninstall result.
#' @export
uninstall_cli <- function(bin_dir = NULL, name = "epwshiftr") {
    checkmate::assert_string(bin_dir, min.chars = 1L, null.ok = TRUE)
    checkmate::assert_string(name, min.chars = 1L)
    spec <- epwshiftr_cli_launcher_spec(bin_dir, name)
    if (!file.exists(spec$path)) {
        return(data.table::data.table(
            path = spec$path,
            bin_dir = spec$bin_dir,
            command = spec$command,
            removed = FALSE,
            message = "launcher not found"
        ))
    }
    content <- readLines(spec$path, warn = FALSE)
    if (!any(grepl("Generated by epwshiftr::install_cli\\(\\)", content)) ||
        !any(grepl("epwshiftr::epwshiftr_cli\\(exit = TRUE\\)", content, fixed = FALSE))) {
        cli::cli_abort("Refusing to remove {.path {spec$path}} because it was not generated by {.fn epwshiftr::install_cli}.")
    }
    removed <- unlink(spec$path, recursive = FALSE, force = TRUE) == 0L
    data.table::data.table(
        path = spec$path,
        bin_dir = spec$bin_dir,
        command = spec$command,
        removed = removed,
        message = if (isTRUE(removed)) "removed launcher" else "failed to remove launcher"
    )
}


epwshiftr_cli_launcher_spec <- function(bin_dir = NULL, name = "epwshiftr") {
    windows <- .Platform$OS.type == "windows"
    if (is.null(bin_dir)) {
        bin_dir <- if (isTRUE(windows)) {
            local_app <- Sys.getenv("LOCALAPPDATA", unset = NA_character_)
            if (is.na(local_app) || !nzchar(local_app)) {
                local_app <- file.path(path.expand("~"), "AppData", "Local")
            }
            file.path(local_app, "epwshiftr", "bin")
        } else {
            file.path(path.expand("~"), ".local", "bin")
        }
    }
    bin_dir <- path.expand(bin_dir)
    bin_dir <- normalizePath(bin_dir, mustWork = dir.exists(bin_dir), winslash = "/")
    command <- name
    file_name <- name
    if (isTRUE(windows) && !grepl("[.]cmd$", file_name, ignore.case = TRUE)) {
        file_name <- paste0(file_name, ".cmd")
        command <- file_name
    }
    list(
        windows = windows,
        bin_dir = bin_dir,
        command = command,
        path = file.path(bin_dir, file_name)
    )
}


epwshiftr_cli_launcher_content <- function(windows = .Platform$OS.type == "windows") {
    rscript <- file.path(R.home("bin"), if (isTRUE(windows)) "Rscript.exe" else "Rscript")
    rscript <- normalizePath(rscript, mustWork = FALSE, winslash = if (isTRUE(windows)) "\\" else "/")
    expr <- "epwshiftr::epwshiftr_cli(exit = TRUE)"
    if (isTRUE(windows)) {
        return(c(
            "@echo off",
            "rem Generated by epwshiftr::install_cli()",
            sprintf("\"%s\" --vanilla -e \"%s\" %%*", rscript, expr)
        ))
    }
    c(
        "#!/bin/sh",
        "# Generated by epwshiftr::install_cli()",
        sprintf("exec %s --vanilla -e %s \"$@\"", shQuote(rscript), shQuote(expr))
    )
}


epwshiftr_cli_bin_in_path <- function(bin_dir) {
    path <- Sys.getenv("PATH", unset = "")
    if (!nzchar(path)) {
        return(FALSE)
    }
    dirs <- strsplit(path, .Platform$path.sep, fixed = TRUE)[[1L]]
    dirs <- dirs[nzchar(dirs)]
    if (!length(dirs)) {
        return(FALSE)
    }
    normalized <- vapply(dirs, normalizePath, character(1L), mustWork = FALSE, winslash = "/")
    normalizePath(bin_dir, mustWork = FALSE, winslash = "/") %in% normalized
}
