#' Run the epwshiftr command line interface
#'
#' @description
#' `epwshiftr_cli()` is the package-level entry point used by the optional
#' `epwshiftr` launcher. It exposes a small ESGF store workflow interface and
#' returns status metadata when `exit = FALSE`, which makes it testable from R.
#'
#' @param args Command line arguments. Defaults to
#'        `commandArgs(trailingOnly = TRUE)`.
#' @param exit Whether to terminate the current R process with the command
#'        status. Default: `FALSE`.
#'
#' @return Invisibly, a list with `status`, `result`, and `error`.
#' @export
epwshiftr_cli <- function(args = commandArgs(trailingOnly = TRUE), exit = FALSE) {
    checkmate::assert_character(args, any.missing = FALSE)
    checkmate::assert_flag(exit)

    parsed <- NULL
    status <- 0L
    result <- NULL
    error <- NULL
    tryCatch(
        {
            parsed <- epwshiftr_cli_parse_globals(args)
            result <- epwshiftr_cli_dispatch(parsed)
            epwshiftr_cli_emit_result(result, json = parsed$json, quiet = parsed$quiet)
        },
        epwshiftr_cli_usage_error = function(e) {
            status <<- 2L
            error <<- conditionMessage(e)
            epwshiftr_cli_emit_error(error, json = epwshiftr_cli_has_flag(args, "--json"), quiet = epwshiftr_cli_has_flag(args, "--quiet"), status = status)
        },
        error = function(e) {
            status <<- 1L
            error <<- conditionMessage(e)
            epwshiftr_cli_emit_error(error, json = epwshiftr_cli_has_flag(args, "--json"), quiet = epwshiftr_cli_has_flag(args, "--quiet"), status = status)
        }
    )
    out <- list(status = status, result = result, error = error)
    if (isTRUE(exit)) {
        quit(status = status, save = "no")
    }
    invisible(out)
}

#' Install the epwshiftr command launcher
#'
#' @description
#' `install_cli()` writes a small platform launcher that runs the current
#' `Rscript` with `epwshiftr::epwshiftr_cli(exit = TRUE)`. It does not modify
#' shell profiles or `PATH`.
#'
#' @param bin_dir Directory where the launcher should be written. Defaults to
#'        `~/.local/bin` on macOS/Linux and
#'        `%LOCALAPPDATA%/epwshiftr/bin` on Windows.
#' @param name Launcher command name. Default: `"epwshiftr"`.
#' @param overwrite Whether to replace an existing launcher. Default: `FALSE`.
#'
#' @return A data.table describing the installed launcher.
#' @export
install_cli <- function(bin_dir = NULL, name = "epwshiftr", overwrite = FALSE) {
    checkmate::assert_string(bin_dir, min.chars = 1L, null.ok = TRUE)
    checkmate::assert_string(name, min.chars = 1L)
    checkmate::assert_flag(overwrite)
    if (!grepl("^[A-Za-z][A-Za-z0-9._-]*$", name)) {
        cli::cli_abort("{.arg name} must start with a letter and contain only letters, digits, '.', '_', or '-'.")
    }

    spec <- epwshiftr_cli_launcher_spec(bin_dir, name)
    if (file.exists(spec$path) && !isTRUE(overwrite)) {
        cli::cli_abort("Launcher already exists at {.path {spec$path}}. Use {.code overwrite = TRUE} to replace it.")
    }
    if (!dir.exists(spec$bin_dir)) {
        dir.create(spec$bin_dir, recursive = TRUE, showWarnings = FALSE)
    }
    if (!dir.exists(spec$bin_dir)) {
        cli::cli_abort("Failed to create launcher directory: {.path {spec$bin_dir}}.")
    }
    spec$bin_dir <- normalizePath(spec$bin_dir, mustWork = TRUE, winslash = "/")
    spec$path <- file.path(spec$bin_dir, basename(spec$path))

    writeLines(epwshiftr_cli_launcher_content(spec$windows), spec$path, useBytes = TRUE)
    if (!isTRUE(spec$windows)) {
        Sys.chmod(spec$path, mode = "0755")
    }
    in_path <- epwshiftr_cli_bin_in_path(spec$bin_dir)
    if (!isTRUE(in_path)) {
        cli::cli_inform("Launcher installed at {.path {spec$path}}, but {.path {spec$bin_dir}} is not currently on PATH.")
    }
    data.table::data.table(
        path = spec$path,
        bin_dir = spec$bin_dir,
        command = spec$command,
        in_path = in_path,
        installed = TRUE
    )
}

#' Uninstall the epwshiftr command launcher
#'
#' @description
#' Remove a launcher generated by `install_cli()`.
#'
#' @inheritParams install_cli
#'
#' @return A data.table describing the uninstall result.
#' @export
uninstall_cli <- function(bin_dir = NULL, name = "epwshiftr") {
    checkmate::assert_string(bin_dir, min.chars = 1L, null.ok = TRUE)
    checkmate::assert_string(name, min.chars = 1L)
    spec <- epwshiftr_cli_launcher_spec(bin_dir, name)
    if (!file.exists(spec$path)) {
        return(data.table::data.table(
            path = spec$path,
            bin_dir = spec$bin_dir,
            command = spec$command,
            removed = FALSE,
            message = "launcher not found"
        ))
    }
    content <- readLines(spec$path, warn = FALSE)
    if (!any(grepl("Generated by epwshiftr::install_cli\\(\\)", content)) ||
        !any(grepl("epwshiftr::epwshiftr_cli\\(exit = TRUE\\)", content, fixed = FALSE))) {
        cli::cli_abort("Refusing to remove {.path {spec$path}} because it was not generated by {.fn epwshiftr::install_cli}.")
    }
    removed <- unlink(spec$path, recursive = FALSE, force = TRUE) == 0L
    data.table::data.table(
        path = spec$path,
        bin_dir = spec$bin_dir,
        command = spec$command,
        removed = removed,
        message = if (isTRUE(removed)) "removed launcher" else "failed to remove launcher"
    )
}

epwshiftr_cli_parse_globals <- function(args) {
    out <- list(
        store = NULL,
        json = FALSE,
        quiet = FALSE,
        help = FALSE,
        args = character()
    )
    i <- 1L
    while (i <= length(args)) {
        arg <- args[[i]]
        if (identical(arg, "--store")) {
            if (i == length(args)) {
                epwshiftr_cli_usage_abort("--store requires a path.")
            }
            out$store <- args[[i + 1L]]
            i <- i + 2L
            next
        }
        if (startsWith(arg, "--store=")) {
            out$store <- sub("^--store=", "", arg)
            if (!nzchar(out$store)) {
                epwshiftr_cli_usage_abort("--store requires a path.")
            }
            i <- i + 1L
            next
        }
        if (identical(arg, "--json")) {
            out$json <- TRUE
            i <- i + 1L
            next
        }
        if (identical(arg, "--quiet")) {
            out$quiet <- TRUE
            i <- i + 1L
            next
        }
        if (arg %in% c("--help", "-h")) {
            out$help <- TRUE
            i <- i + 1L
            next
        }
        out$args <- c(out$args, arg)
        i <- i + 1L
    }
    out
}

epwshiftr_cli_dispatch <- function(parsed) {
    if (isTRUE(parsed$help)) {
        return(epwshiftr_cli_usage())
    }
    args <- parsed$args
    if (length(args) < 2L) {
        epwshiftr_cli_usage_abort(epwshiftr_cli_usage())
    }

    store <- EsgStore$new(path = parsed$store)
    on.exit(store$close(), add = TRUE)

    group <- args[[1L]]
    command <- args[[2L]]
    rest <- args[-seq_len(2L)]

    if (identical(group, "query")) {
        return(epwshiftr_cli_query(store, command, rest))
    }
    if (identical(group, "download")) {
        return(epwshiftr_cli_download(store, command, rest))
    }
    if (identical(group, "workflow")) {
        return(epwshiftr_cli_workflow(store, command, rest))
    }
    if (identical(group, "storage")) {
        return(epwshiftr_cli_storage(store, command, rest))
    }
    epwshiftr_cli_usage_abort(sprintf("Unknown command group: %s", group))
}

epwshiftr_cli_query <- function(store, command, args) {
    if (identical(command, "list")) {
        parsed <- epwshiftr_cli_parse_command(args)
        epwshiftr_cli_assert_no_positionals(parsed)
        return(store$queries())
    }
    if (identical(command, "search")) {
        parsed <- epwshiftr_cli_parse_command(
            args,
            flags = c("--all", "--dry-run"),
            options = c("--index-node", "--type", "--fields", "--limit")
        )
        query <- epwshiftr_cli_search_query(parsed)
        type <- if (is.null(parsed$options[["--type"]])) "Dataset" else parsed$options[["--type"]]
        fields <- epwshiftr_cli_csv(parsed$options[["--fields"]])
        limit <- if (isTRUE(parsed$flags[["--all"]])) {
            FALSE
        } else if (is.null(parsed$options[["--limit"]])) {
            TRUE
        } else {
            epwshiftr_cli_count(parsed$options[["--limit"]], "--limit")
        }
        if (isTRUE(parsed$flags[["--dry-run"]])) {
            return(list(
                url = query$url(),
                type = type,
                fields = fields,
                all = parsed$flags[["--all"]],
                limit = limit,
                query = query$state(null = TRUE)
            ))
        }
        result <- query$collect(type = type, fields = fields, all = parsed$flags[["--all"]], limit = limit)
        return(result$to_data_table(fields = fields))
    }
    if (identical(command, "add")) {
        parsed <- epwshiftr_cli_parse_command(args, flags = "--track", options = c("--query-file", "--label"))
        epwshiftr_cli_assert_no_positionals(parsed)
        file <- parsed$options[["--query-file"]]
        if (is.null(file)) {
            epwshiftr_cli_usage_abort("query add requires --query-file.")
        }
        query <- esg_query()$load(file)
        before <- store$queries()$query_id
        query_id <- store$add_query(query, label = parsed$options[["--label"]], track = parsed$flags[["--track"]])
        query_id <- epwshiftr_cli_added_query_id(store, query_id, before)
        return(epwshiftr_cli_query_row(store, query_id))
    }
    if (identical(command, "show")) {
        parsed <- epwshiftr_cli_parse_command(args, flags = c("--files", "--updates", "--changes"))
        query_id <- epwshiftr_cli_required_position(parsed, "query_id")
        wanted_query_id <- query_id
        query <- store$queries()
        query <- query[query[["query_id"]] == wanted_query_id]
        if (!nrow(query)) {
            cli::cli_abort("Unknown query ID: {.val {query_id}}.")
        }
        out <- list(
            query = query[],
            tags = store$query_tags(query_id),
            graph = store$query_graph(query_id = query_id, direction = "both"),
            status = store$query_status(query_id)
        )
        if (isTRUE(parsed$flags[["--files"]])) {
            out$files <- store$query_files(query_id)
        }
        if (isTRUE(parsed$flags[["--updates"]])) {
            out$updates <- store$query_updates(query_id)
        }
        if (isTRUE(parsed$flags[["--changes"]])) {
            updates <- store$query_updates(query_id, latest = TRUE)
            out$changes <- if (nrow(updates)) {
                store$query_changes(update_id = updates$update_id)
            } else {
                data.table::data.table()
            }
        }
        return(out)
    }
    if (identical(command, "status")) {
        parsed <- epwshiftr_cli_parse_command(args)
        query_id <- epwshiftr_cli_optional_position(parsed, "query_id")
        return(store$query_status(query_id))
    }
    if (identical(command, "files")) {
        parsed <- epwshiftr_cli_parse_command(args, options = "--status")
        query_id <- epwshiftr_cli_required_position(parsed, "query_id")
        return(store$query_files(query_id, status = epwshiftr_cli_csv(parsed$options[["--status"]])))
    }
    if (identical(command, "updates")) {
        parsed <- epwshiftr_cli_parse_command(args, flags = "--latest")
        query_id <- epwshiftr_cli_optional_position(parsed, "query_id")
        return(store$query_updates(query_id = query_id, latest = parsed$flags[["--latest"]]))
    }
    if (identical(command, "changes")) {
        parsed <- epwshiftr_cli_parse_command(args, flags = "--latest", options = c("--update", "--type"))
        query_id <- epwshiftr_cli_optional_position(parsed, "query_id")
        update_id <- parsed$options[["--update"]]
        if (is.null(update_id) && isTRUE(parsed$flags[["--latest"]])) {
            updates <- store$query_updates(query_id = query_id, latest = TRUE)
            if (!nrow(updates)) {
                return(data.table::data.table())
            }
            update_id <- if (nrow(updates)) updates$update_id else character()
        }
        return(store$query_changes(
            update_id = epwshiftr_cli_empty_to_null(update_id),
            query_id = query_id,
            change_type = epwshiftr_cli_csv(parsed$options[["--type"]])
        ))
    }
    if (identical(command, "tags")) {
        parsed <- epwshiftr_cli_parse_command(args)
        query_id <- epwshiftr_cli_optional_position(parsed, "query_id")
        return(store$query_tags(query_id))
    }
    if (identical(command, "track")) {
        parsed <- epwshiftr_cli_parse_command(args)
        query_id <- epwshiftr_cli_required_position(parsed, "query_id")
        store$track_query(query_id)
        return(epwshiftr_cli_query_row(store, query_id))
    }
    if (identical(command, "untrack")) {
        parsed <- epwshiftr_cli_parse_command(args)
        query_id <- epwshiftr_cli_required_position(parsed, "query_id")
        store$untrack_query(query_id)
        return(epwshiftr_cli_query_row(store, query_id))
    }
    if (identical(command, "tag")) {
        parsed <- epwshiftr_cli_parse_command(args, flags = "--replace")
        if (length(parsed$positionals) < 2L) {
            epwshiftr_cli_usage_abort("Missing required arguments: query_id and tag.")
        }
        query_id <- parsed$positionals[[1L]]
        tags <- parsed$positionals[-1L]
        return(store$tag_query(query_id, tags, replace = parsed$flags[["--replace"]]))
    }
    if (identical(command, "untag")) {
        parsed <- epwshiftr_cli_parse_command(args)
        if (!length(parsed$positionals)) {
            epwshiftr_cli_usage_abort("Missing required argument: query_id.")
        }
        query_id <- parsed$positionals[[1L]]
        tags <- if (length(parsed$positionals) > 1L) parsed$positionals[-1L] else NULL
        return(store$untag_query(query_id, tags))
    }
    if (identical(command, "remove")) {
        parsed <- epwshiftr_cli_parse_command(args, flags = "--execute", options = "--delete")
        query_id <- epwshiftr_cli_required_position(parsed, "query_id")
        delete <- parsed$options[["--delete"]]
        if (is.null(delete)) {
            delete <- "none"
        }
        if (!delete %in% c("none", "orphaned")) {
            epwshiftr_cli_usage_abort("--delete must be one of: none, orphaned.")
        }
        if (isTRUE(parsed$flags[["--execute"]])) {
            return(store$remove_query(query_id, delete = delete))
        }
        return(epwshiftr_cli_query_remove_preview(store, query_id, delete))
    }
    if (identical(command, "preview")) {
        parsed <- epwshiftr_cli_parse_command(args, flags = "--detail")
        query_id <- epwshiftr_cli_optional_position(parsed, "query_id")
        return(store$preview_update_queries(query_id = query_id, detail = parsed$flags[["--detail"]]))
    }
    if (identical(command, "update")) {
        parsed <- epwshiftr_cli_parse_command(args)
        query_id <- epwshiftr_cli_optional_position(parsed, "query_id")
        return(store$update_queries(query_id = query_id))
    }
    epwshiftr_cli_usage_abort(sprintf("Unknown query command: %s", command))
}

epwshiftr_cli_download <- function(store, command, args) {
    if (identical(command, "config")) {
        return(epwshiftr_cli_download_config(store, args))
    }
    if (identical(command, "preflight")) {
        parsed <- epwshiftr_cli_parse_command(
            args,
            flags = c("--probe", "--no-probe"),
            options = c("--replica", "--service", "--strategy", "--probe-concurrency", "--probe-cache-seconds")
        )
        query_id <- epwshiftr_cli_required_position(parsed, "query_id")
        return(do.call(store$download_preflight, c(
            list(query_id = query_id, downloader = epwshiftr_cli_downloader(store)),
            epwshiftr_cli_download_plan_args(parsed)
        )))
    }
    if (identical(command, "run")) {
        parsed <- epwshiftr_cli_parse_command(
            args,
            flags = c("--probe", "--no-probe", "--overwrite", "--no-resume", "--no-progress"),
            options = c("--replica", "--service", "--strategy", "--probe-concurrency", "--probe-cache-seconds", "--session-label")
        )
        query_id <- epwshiftr_cli_required_position(parsed, "query_id")
        return(do.call(store$download_query, c(
            list(
                query_id = query_id,
                downloader = epwshiftr_cli_downloader(store),
                session_label = parsed$options[["--session-label"]],
                overwrite = parsed$flags[["--overwrite"]],
                resume = !parsed$flags[["--no-resume"]],
                progress = !parsed$flags[["--no-progress"]]
            ),
            epwshiftr_cli_download_plan_args(parsed)
        )))
    }
    if (identical(command, "status")) {
        parsed <- epwshiftr_cli_parse_command(args, options = c("--query", "--session"))
        epwshiftr_cli_assert_no_positionals(parsed)
        return(store$download_status(
            query_id = parsed$options[["--query"]],
            session_id = parsed$options[["--session"]],
            downloader = epwshiftr_cli_downloader(store)
        ))
    }
    if (identical(command, "sessions")) {
        parsed <- epwshiftr_cli_parse_command(args)
        epwshiftr_cli_assert_no_positionals(parsed)
        return(epwshiftr_cli_downloader(store)$sessions())
    }
    if (identical(command, "tasks")) {
        parsed <- epwshiftr_cli_parse_command(args, options = c("--session", "--status"))
        epwshiftr_cli_assert_no_positionals(parsed)
        return(epwshiftr_cli_downloader(store)$tasks(
            session_id = parsed$options[["--session"]],
            status = epwshiftr_cli_csv(parsed$options[["--status"]])
        ))
    }
    if (identical(command, "events")) {
        parsed <- epwshiftr_cli_parse_command(args, options = c("--session", "--task"))
        epwshiftr_cli_assert_no_positionals(parsed)
        return(epwshiftr_cli_downloader(store)$events(
            session_id = parsed$options[["--session"]],
            task_id = epwshiftr_cli_csv(parsed$options[["--task"]])
        ))
    }
    if (identical(command, "resume")) {
        parsed <- epwshiftr_cli_parse_command(args, flags = c("--overwrite", "--no-progress"), options = c("--session", "--task"))
        epwshiftr_cli_assert_no_positionals(parsed)
        downloader <- epwshiftr_cli_downloader(store)
        out <- downloader$resume(
            session_id = parsed$options[["--session"]],
            task_id = epwshiftr_cli_csv(parsed$options[["--task"]]),
            overwrite = parsed$flags[["--overwrite"]],
            progress = !parsed$flags[["--no-progress"]]
        )
        store$sync_downloads(downloader)
        return(out)
    }
    if (identical(command, "verify")) {
        parsed <- epwshiftr_cli_parse_command(args, options = c("--session", "--task"))
        epwshiftr_cli_assert_no_positionals(parsed)
        downloader <- epwshiftr_cli_downloader(store)
        out <- downloader$verify(
            session_id = parsed$options[["--session"]],
            task_id = epwshiftr_cli_csv(parsed$options[["--task"]])
        )
        store$sync_downloads(downloader)
        return(out)
    }
    if (identical(command, "cancel")) {
        parsed <- epwshiftr_cli_parse_command(args, options = c("--session", "--task"))
        epwshiftr_cli_assert_no_positionals(parsed)
        return(epwshiftr_cli_downloader(store)$cancel(
            session_id = parsed$options[["--session"]],
            task_id = epwshiftr_cli_csv(parsed$options[["--task"]])
        ))
    }
    if (identical(command, "nodes")) {
        parsed <- epwshiftr_cli_parse_command(args, options = "--service")
        epwshiftr_cli_assert_no_positionals(parsed)
        return(epwshiftr_cli_downloader(store)$data_nodes(service = parsed$options[["--service"]]))
    }
    if (identical(command, "reset-nodes")) {
        parsed <- epwshiftr_cli_parse_command(args, flags = "--execute", options = c("--node", "--service"))
        epwshiftr_cli_assert_no_positionals(parsed)
        downloader <- epwshiftr_cli_downloader(store)
        if (isTRUE(parsed$flags[["--execute"]])) {
            return(downloader$reset_data_nodes(data_node = parsed$options[["--node"]], service = parsed$options[["--service"]]))
        }
        nodes <- downloader$data_nodes(service = parsed$options[["--service"]])
        if (!is.null(parsed$options[["--node"]]) && nrow(nodes)) {
            nodes <- nodes[nodes[["data_node"]] == parsed$options[["--node"]]]
        }
        nodes[, dry_run := TRUE]
        return(nodes[])
    }
    if (identical(command, "retry")) {
        parsed <- epwshiftr_cli_parse_command(args, flags = "--run", options = c("--query", "--session", "--status"))
        epwshiftr_cli_assert_no_positionals(parsed)
        status <- epwshiftr_cli_csv(parsed$options[["--status"]])
        if (is.null(status)) {
            status <- c("error", "cancelled")
        }
        return(store$retry_downloads(
            query_id = parsed$options[["--query"]],
            session_id = parsed$options[["--session"]],
            downloader = epwshiftr_cli_downloader(store),
            status = status,
            run = parsed$flags[["--run"]]
        ))
    }
    epwshiftr_cli_usage_abort(sprintf("Unknown download command: %s", command))
}

epwshiftr_cli_workflow <- function(store, command, args) {
    if (identical(command, "report")) {
        parsed <- epwshiftr_cli_parse_command(args, options = "--query")
        epwshiftr_cli_assert_no_positionals(parsed)
        return(store$workflow_report(query_id = parsed$options[["--query"]], downloader = epwshiftr_cli_downloader(store)))
    }
    epwshiftr_cli_usage_abort(sprintf("Unknown workflow command: %s", command))
}

epwshiftr_cli_storage <- function(store, command, args) {
    if (identical(command, "layout")) {
        if (!length(args)) {
            epwshiftr_cli_usage_abort("Missing storage layout command: show or set.")
        }
        action <- args[[1L]]
        rest <- args[-1L]
        if (identical(action, "show")) {
            parsed <- epwshiftr_cli_parse_command(rest)
            epwshiftr_cli_assert_no_positionals(parsed)
            return(store$download_layout())
        }
        if (identical(action, "set")) {
            parsed <- epwshiftr_cli_parse_command(
                rest,
                options = c("--layout", "--template", "--include-version", "--collision", "--missing")
            )
            epwshiftr_cli_assert_no_positionals(parsed)
            layout <- parsed$options[["--layout"]]
            if (is.null(layout)) {
                epwshiftr_cli_usage_abort("storage layout set requires --layout.")
            }
            store$set_download_layout(
                layout = layout,
                template = parsed$options[["--template"]],
                include_version = epwshiftr_cli_bool(parsed$options[["--include-version"]], "--include-version", default = TRUE),
                collision = if (is.null(parsed$options[["--collision"]])) "error" else parsed$options[["--collision"]],
                missing = if (is.null(parsed$options[["--missing"]])) "fallback" else parsed$options[["--missing"]]
            )
            return(store$download_layout())
        }
        epwshiftr_cli_usage_abort(sprintf("Unknown storage layout command: %s", action))
    }
    if (identical(command, "report")) {
        parsed <- epwshiftr_cli_parse_command(args, flags = "--detail")
        epwshiftr_cli_assert_no_positionals(parsed)
        return(store$storage_report(detail = parsed$flags[["--detail"]]))
    }
    if (identical(command, "validate")) {
        parsed <- epwshiftr_cli_parse_command(args, flags = "--checksum", options = "--query")
        epwshiftr_cli_assert_no_positionals(parsed)
        return(store$validate_files(query_id = parsed$options[["--query"]], checksum = parsed$flags[["--checksum"]]))
    }
    if (identical(command, "repair")) {
        parsed <- epwshiftr_cli_parse_command(args, flags = "--execute")
        epwshiftr_cli_assert_no_positionals(parsed)
        return(store$repair_files(dry_run = !parsed$flags[["--execute"]]))
    }
    if (identical(command, "cleanup")) {
        parsed <- epwshiftr_cli_parse_command(args, flags = "--execute", options = c("--scope", "--older-than"))
        epwshiftr_cli_assert_no_positionals(parsed)
        scope <- epwshiftr_cli_csv(parsed$options[["--scope"]])
        if (is.null(scope)) {
            scope <- c("tmp", "orphan_records", "untracked_files", "missing_records")
        }
        older_than <- epwshiftr_cli_count(parsed$options[["--older-than"]], "--older-than", positive = FALSE)
        return(store$cleanup_downloads(scope = scope, dry_run = !parsed$flags[["--execute"]], older_than = older_than))
    }
    epwshiftr_cli_usage_abort(sprintf("Unknown storage command: %s", command))
}

epwshiftr_cli_parse_command <- function(args, flags = character(), options = character()) {
    flag_values <- stats::setNames(rep(FALSE, length(flags)), flags)
    option_values <- stats::setNames(rep(list(NULL), length(options)), options)
    positionals <- character()
    i <- 1L
    while (i <= length(args)) {
        arg <- args[[i]]
        if (arg %in% flags) {
            flag_values[[arg]] <- TRUE
            i <- i + 1L
            next
        }
        option_match <- options[startsWith(arg, paste0(options, "="))]
        if (length(option_match)) {
            option <- option_match[[1L]]
            option_values[[option]] <- sub(sprintf("^%s=", option), "", arg)
            if (!nzchar(option_values[[option]])) {
                epwshiftr_cli_usage_abort(sprintf("%s requires a value.", option))
            }
            i <- i + 1L
            next
        }
        if (arg %in% options) {
            if (i == length(args)) {
                epwshiftr_cli_usage_abort(sprintf("%s requires a value.", arg))
            }
            option_values[[arg]] <- args[[i + 1L]]
            i <- i + 2L
            next
        }
        if (startsWith(arg, "--")) {
            epwshiftr_cli_usage_abort(sprintf("Unknown option: %s", arg))
        }
        positionals <- c(positionals, arg)
        i <- i + 1L
    }
    list(positionals = positionals, flags = flag_values, options = option_values)
}

epwshiftr_cli_optional_position <- function(parsed, name) {
    if (length(parsed$positionals) > 1L) {
        epwshiftr_cli_usage_abort(sprintf("Too many positional arguments for %s.", name))
    }
    if (!length(parsed$positionals)) {
        return(NULL)
    }
    parsed$positionals[[1L]]
}

epwshiftr_cli_required_position <- function(parsed, name) {
    if (!length(parsed$positionals)) {
        epwshiftr_cli_usage_abort(sprintf("Missing required argument: %s", name))
    }
    if (length(parsed$positionals) > 1L) {
        epwshiftr_cli_usage_abort(sprintf("Too many positional arguments for %s.", name))
    }
    parsed$positionals[[1L]]
}

epwshiftr_cli_assert_no_positionals <- function(parsed) {
    if (length(parsed$positionals)) {
        epwshiftr_cli_usage_abort(sprintf("Unexpected argument: %s", parsed$positionals[[1L]]))
    }
    invisible(NULL)
}

epwshiftr_cli_csv <- function(value) {
    if (is.null(value) || !length(value)) {
        return(NULL)
    }
    value <- unlist(strsplit(value, ",", fixed = TRUE), use.names = FALSE)
    value <- trimws(value)
    value <- value[nzchar(value)]
    if (!length(value)) {
        return(NULL)
    }
    unique(value)
}

epwshiftr_cli_search_query <- function(parsed) {
    index_node <- parsed$options[["--index-node"]]
    query <- if (is.null(index_node)) esg_query() else esg_query(index_node)
    params <- epwshiftr_cli_key_value_params(parsed$positionals)
    if (length(params)) {
        query <- epwshiftr_cli_apply_search_params(query, params)
    }
    query
}

epwshiftr_cli_apply_search_params <- function(query, params) {
    for (key in names(params)) {
        value <- params[[key]]
        method <- tryCatch(query[[key]], error = function(e) NULL)
        if (is.function(method)) {
            query <- method(value)
        } else {
            query <- do.call(query$params, stats::setNames(list(value), key))
        }
    }
    query
}

epwshiftr_cli_key_value_params <- function(values) {
    out <- list()
    for (value in values) {
        if (!grepl("=", value, fixed = TRUE)) {
            epwshiftr_cli_usage_abort(sprintf("Expected key=value query parameter, got: %s", value))
        }
        parts <- strsplit(value, "=", fixed = TRUE)[[1L]]
        key <- parts[[1L]]
        raw <- paste(parts[-1L], collapse = "=")
        if (!nzchar(key)) {
            epwshiftr_cli_usage_abort(sprintf("Query parameter has an empty key: %s", value))
        }
        parsed <- epwshiftr_cli_query_param_value(raw)
        if (key %in% names(out)) {
            out[[key]] <- c(out[[key]], parsed)
        } else {
            out[[key]] <- parsed
        }
    }
    out
}

epwshiftr_cli_query_param_value <- function(value) {
    values <- epwshiftr_cli_csv(value)
    if (is.null(values)) {
        return("")
    }
    lowered <- tolower(values)
    if (length(values) == 1L && lowered %in% c("true", "false")) {
        return(identical(lowered, "true"))
    }
    values
}

epwshiftr_cli_count <- function(value, name, positive = TRUE) {
    if (is.null(value)) {
        return(NULL)
    }
    out <- suppressWarnings(as.numeric(value))
    if (length(out) != 1L || is.na(out)) {
        epwshiftr_cli_usage_abort(sprintf("%s must be a number.", name))
    }
    checkmate::assert_count(out, positive = positive, .var.name = name)
    as.integer(out)
}

epwshiftr_cli_bool <- function(value, name, default = NULL) {
    if (is.null(value)) {
        return(default)
    }
    normalized <- tolower(trimws(value))
    if (normalized %in% c("true", "t", "1", "yes", "y")) {
        return(TRUE)
    }
    if (normalized %in% c("false", "f", "0", "no", "n")) {
        return(FALSE)
    }
    epwshiftr_cli_usage_abort(sprintf("%s must be true or false.", name))
}

epwshiftr_cli_download_plan_args <- function(parsed) {
    args <- list()
    for (name in c("--replica", "--service", "--strategy")) {
        if (!is.null(parsed$options[[name]])) {
            key <- gsub("-", "_", sub("^--", "", name))
            args[[key]] <- parsed$options[[name]]
        }
    }
    if (isTRUE(parsed$flags[["--probe"]]) && isTRUE(parsed$flags[["--no-probe"]])) {
        epwshiftr_cli_usage_abort("Use only one of --probe or --no-probe.")
    }
    if (isTRUE(parsed$flags[["--probe"]])) {
        args$probe <- TRUE
    }
    if (isTRUE(parsed$flags[["--no-probe"]])) {
        args$probe <- FALSE
    }
    if (!is.null(parsed$options[["--probe-concurrency"]])) {
        args$probe_concurrency <- epwshiftr_cli_count(parsed$options[["--probe-concurrency"]], "--probe-concurrency")
    }
    if (!is.null(parsed$options[["--probe-cache-seconds"]])) {
        args$probe_cache_seconds <- epwshiftr_cli_count(parsed$options[["--probe-cache-seconds"]], "--probe-cache-seconds")
    }
    args
}

epwshiftr_cli_download_config <- function(store, args) {
    if (!length(args)) {
        epwshiftr_cli_usage_abort("Missing download config command: show or set.")
    }
    action <- args[[1L]]
    rest <- args[-1L]
    if (identical(action, "show")) {
        parsed <- epwshiftr_cli_parse_command(rest)
        epwshiftr_cli_assert_no_positionals(parsed)
        return(epwshiftr_cli_downloader_config(epwshiftr_cli_downloader(store)))
    }
    if (identical(action, "set")) {
        parsed <- epwshiftr_cli_parse_command(
            rest,
            options = c(
                "--workers", "--retries", "--timeout", "--connect-timeout",
                "--proxy", "--useragent", "--ssl-verifypeer",
                "--chunk-size", "--bandwidth-limit", "--low-speed-limit", "--low-speed-time",
                "--host-concurrency", "--disk-preflight", "--min-free-space",
                "--cooldown-after-failures", "--cooldown-seconds", "--history-ttl-seconds", "--min-attempts"
            )
        )
        epwshiftr_cli_assert_no_positionals(parsed)
        current <- epwshiftr_cli_downloader(store)
        network <- current$network_policy
        node_policy <- current$node_policy
        transfer_policy <- current$transfer_policy
        resource_policy <- current$resource_policy
        params <- list(
            retries = current$max_retries,
            timeout = current$timeout,
            ssl_verifypeer = network$ssl_verifypeer,
            proxy = network$proxy,
            connect_timeout = network$connect_timeout,
            useragent = network$useragent,
            n_workers = current$n_workers,
            node_policy = node_policy,
            transfer_policy = transfer_policy,
            resource_policy = resource_policy
        )
        params <- epwshiftr_cli_apply_download_config_options(params, parsed$options)
        paths <- epwshiftr_cli_downloader_paths(store)
        downloader <- do.call(Downloader$new, c(list(
            dest = paths$dest,
            temp = paths$temp,
            manifest = paths$manifest
        ), params))
        downloader$save_config(paths$config)
        return(epwshiftr_cli_downloader_config(downloader))
    }
    epwshiftr_cli_usage_abort(sprintf("Unknown download config command: %s", action))
}

epwshiftr_cli_downloader_paths <- function(store) {
    private <- tryCatch(store$.__enclos_env__$private, error = function(e) NULL)
    if (is.null(private) || is.null(private$download_dir) || is.null(private$tmp_download_dir)) {
        cli::cli_abort("Cannot resolve store downloader paths.")
    }
    list(
        dest = private$download_dir,
        temp = private$tmp_download_dir,
        manifest = file.path(private$download_dir, "_downloader", "manifest.duckdb"),
        config = file.path(private$download_dir, "_downloader", "config.json")
    )
}

epwshiftr_cli_downloader <- function(store, ...) {
    paths <- epwshiftr_cli_downloader_paths(store)
    config <- if (file.exists(paths$config)) paths$config else NULL
    Downloader$new(
        dest = paths$dest,
        temp = paths$temp,
        manifest = paths$manifest,
        config = config,
        ...
    )
}

epwshiftr_cli_downloader_config <- function(downloader) {
    list(
        config_file = downloader$config_file,
        manifest = downloader$manifest,
        data_dir = downloader$data_dir,
        tmp_dir = downloader$tmp_dir,
        retries = downloader$max_retries,
        timeout = downloader$timeout,
        n_workers = downloader$n_workers,
        network_policy = downloader$network_policy,
        node_policy = downloader$node_policy,
        transfer_policy = downloader$transfer_policy,
        resource_policy = downloader$resource_policy
    )
}

epwshiftr_cli_apply_download_config_options <- function(params, options) {
    set_count <- function(option, target, positive = TRUE) {
        if (!is.null(options[[option]])) {
            params[[target]] <<- epwshiftr_cli_count(options[[option]], option, positive = positive)
        }
    }
    set_nullable_count <- function(option, policy, field, positive = TRUE) {
        if (!is.null(options[[option]])) {
            params[[policy]][[field]] <<- epwshiftr_cli_count_or_null(options[[option]], option, positive = positive)
        }
    }
    set_count("--workers", "n_workers", positive = FALSE)
    set_count("--retries", "retries")
    set_count("--timeout", "timeout")
    if (!is.null(options[["--connect-timeout"]])) {
        params$connect_timeout <- epwshiftr_cli_count_or_null(options[["--connect-timeout"]], "--connect-timeout")
    }
    if (!is.null(options[["--proxy"]])) {
        params$proxy <- epwshiftr_cli_string_or_null(options[["--proxy"]])
    }
    if (!is.null(options[["--useragent"]])) {
        params$useragent <- epwshiftr_cli_string_or_null(options[["--useragent"]])
    }
    if (!is.null(options[["--ssl-verifypeer"]])) {
        params$ssl_verifypeer <- epwshiftr_cli_bool(options[["--ssl-verifypeer"]], "--ssl-verifypeer")
    }
    set_nullable_count("--chunk-size", "transfer_policy", "chunk_size")
    set_nullable_count("--bandwidth-limit", "transfer_policy", "bandwidth_limit")
    set_nullable_count("--low-speed-limit", "transfer_policy", "low_speed_limit")
    set_nullable_count("--low-speed-time", "transfer_policy", "low_speed_time")
    set_nullable_count("--host-concurrency", "resource_policy", "host_concurrency")
    if (!is.null(options[["--disk-preflight"]])) {
        params$resource_policy$disk_preflight <- epwshiftr_cli_bool(options[["--disk-preflight"]], "--disk-preflight")
    }
    if (!is.null(options[["--min-free-space"]])) {
        params$resource_policy$min_free_space <- epwshiftr_cli_count(options[["--min-free-space"]], "--min-free-space", positive = FALSE)
    }
    if (!is.null(options[["--cooldown-after-failures"]])) {
        params$node_policy$cooldown_after_failures <- epwshiftr_cli_count(options[["--cooldown-after-failures"]], "--cooldown-after-failures")
    }
    if (!is.null(options[["--cooldown-seconds"]])) {
        params$node_policy$cooldown_seconds <- epwshiftr_cli_count(options[["--cooldown-seconds"]], "--cooldown-seconds")
    }
    if (!is.null(options[["--history-ttl-seconds"]])) {
        params$node_policy$history_ttl_seconds <- epwshiftr_cli_count(options[["--history-ttl-seconds"]], "--history-ttl-seconds")
    }
    if (!is.null(options[["--min-attempts"]])) {
        params$node_policy$min_attempts <- epwshiftr_cli_count(options[["--min-attempts"]], "--min-attempts")
    }
    invisible(params)
}

epwshiftr_cli_string_or_null <- function(value) {
    normalized <- tolower(trimws(value))
    if (!nzchar(normalized) || normalized %in% c("none", "null", "na")) {
        return(NULL)
    }
    value
}

epwshiftr_cli_count_or_null <- function(value, name, positive = TRUE) {
    if (is.null(epwshiftr_cli_string_or_null(value))) {
        return(NULL)
    }
    epwshiftr_cli_count(value, name, positive = positive)
}

epwshiftr_cli_empty_to_null <- function(value) {
    if (is.null(value) || !length(value)) {
        return(NULL)
    }
    value
}

epwshiftr_cli_query_remove_preview <- function(store, query_id, delete = "none") {
    query <- epwshiftr_cli_query_row(store, query_id)
    files <- store$query_files(query_id)
    data.table::data.table(
        dry_run = TRUE,
        query_id = query_id,
        delete = delete,
        file_count = as.integer(nrow(files)),
        tag_count = as.integer(nrow(store$query_tags(query_id))),
        dependency_count = as.integer(nrow(store$query_graph(query_id = query_id, direction = "both"))),
        execute_hint = "rerun with --execute to remove the query"
    )
}

epwshiftr_cli_query_row <- function(store, query_id) {
    query_id <- as.character(query_id)
    if (length(query_id) != 1L || is.na(query_id) || !nzchar(query_id)) {
        cli::cli_abort("Expected exactly one query ID.")
    }
    wanted_query_id <- query_id
    query <- store$queries()
    query <- query[query[["query_id"]] == wanted_query_id]
    if (!nrow(query)) {
        cli::cli_abort("Unknown query ID: {.val {query_id}}.")
    }
    query[]
}

epwshiftr_cli_added_query_id <- function(store, query_id, before) {
    query_id <- as.character(query_id)
    after <- store$queries()$query_id
    if (length(query_id) == 1L && query_id %in% after) {
        return(query_id)
    }
    added <- setdiff(after, before)
    if (length(added) == 1L) {
        return(added)
    }
    if (length(query_id) && tail(query_id, 1L) %in% after) {
        return(tail(query_id, 1L))
    }
    cli::cli_abort("Could not resolve the imported query ID.")
}

epwshiftr_cli_emit_result <- function(result, json = FALSE, quiet = FALSE) {
    if (isTRUE(quiet)) {
        return(invisible(NULL))
    }
    if (isTRUE(json)) {
        cat(jsonlite::toJSON(result, dataframe = "rows", POSIXt = "ISO8601", auto_unbox = TRUE, null = "null", pretty = TRUE))
        cat("\n")
        return(invisible(NULL))
    }
    if (is.character(result)) {
        cli::cli_text(paste(result, collapse = "\n"))
    } else {
        print(result)
    }
    invisible(NULL)
}

epwshiftr_cli_emit_error <- function(message, json = FALSE, quiet = FALSE, status = 1L) {
    if (isTRUE(quiet)) {
        return(invisible(NULL))
    }
    if (isTRUE(json)) {
        cat(jsonlite::toJSON(list(status = status, error = message), auto_unbox = TRUE, null = "null", pretty = TRUE))
        cat("\n")
        return(invisible(NULL))
    }
    cli::cli_alert_danger(message)
    invisible(NULL)
}

epwshiftr_cli_usage <- function() {
    c(
        "Usage: epwshiftr [--store PATH] [--json] [--quiet] <group> <command> [options]",
        "",
        "Commands:",
        "  epwshiftr query list",
        "  epwshiftr query search [--index-node URL] [--type Dataset|File|Aggregation] [--dry-run] key=value ...",
        "  epwshiftr query add --query-file PATH [--label LABEL] [--track]",
        "  epwshiftr query show <query_id> [--files] [--updates] [--changes]",
        "  epwshiftr query status [query_id]",
        "  epwshiftr query files <query_id> [--status STATUS]",
        "  epwshiftr query updates [query_id] [--latest]",
        "  epwshiftr query changes [query_id] [--latest] [--update UPDATE_ID] [--type TYPE]",
        "  epwshiftr query tags [query_id]",
        "  epwshiftr query track <query_id>",
        "  epwshiftr query untrack <query_id>",
        "  epwshiftr query tag <query_id> <tag>... [--replace]",
        "  epwshiftr query untag <query_id> [tag...]",
        "  epwshiftr query remove <query_id> [--delete none|orphaned] [--execute]",
        "  epwshiftr query preview [query_id] [--detail]",
        "  epwshiftr query update [query_id]",
        "  epwshiftr download preflight <query_id> [--replica POLICY] [--strategy STRATEGY] [--no-probe]",
        "  epwshiftr download run <query_id> [--session-label LABEL] [--overwrite] [--no-resume] [--no-progress]",
        "  epwshiftr download status [--query QUERY_ID] [--session SESSION_ID]",
        "  epwshiftr download sessions",
        "  epwshiftr download tasks [--session SESSION_ID] [--status STATUS]",
        "  epwshiftr download events [--session SESSION_ID] [--task TASK_ID]",
        "  epwshiftr download resume [--session SESSION_ID] [--task TASK_ID] [--overwrite] [--no-progress]",
        "  epwshiftr download verify [--session SESSION_ID] [--task TASK_ID]",
        "  epwshiftr download cancel [--session SESSION_ID] [--task TASK_ID]",
        "  epwshiftr download nodes [--service HTTPServer]",
        "  epwshiftr download reset-nodes [--node HOST] [--service HTTPServer] [--execute]",
        "  epwshiftr download retry [--query QUERY_ID] [--session SESSION_ID] [--status STATUS] [--run]",
        "  epwshiftr download config show",
        "  epwshiftr download config set [--workers N] [--timeout SECONDS] [--bandwidth-limit BYTES|none]",
        "  epwshiftr workflow report [--query QUERY_ID]",
        "  epwshiftr storage layout show",
        "  epwshiftr storage layout set --layout flat|dataset|drs|template [--template TEMPLATE]",
        "  epwshiftr storage report [--detail]",
        "  epwshiftr storage validate [--query QUERY_ID] [--checksum]",
        "  epwshiftr storage repair [--execute]",
        "  epwshiftr storage cleanup [--scope SCOPE] [--older-than SECONDS] [--execute]"
    )
}

epwshiftr_cli_usage_abort <- function(message) {
    stop(structure(
        list(message = paste(message, collapse = "\n"), call = NULL),
        class = c("epwshiftr_cli_usage_error", "error", "condition")
    ))
}

epwshiftr_cli_has_flag <- function(args, flag) {
    any(args %in% flag)
}

epwshiftr_cli_launcher_spec <- function(bin_dir = NULL, name = "epwshiftr") {
    windows <- .Platform$OS.type == "windows"
    if (is.null(bin_dir)) {
        bin_dir <- if (isTRUE(windows)) {
            local_app <- Sys.getenv("LOCALAPPDATA", unset = NA_character_)
            if (is.na(local_app) || !nzchar(local_app)) {
                local_app <- file.path(path.expand("~"), "AppData", "Local")
            }
            file.path(local_app, "epwshiftr", "bin")
        } else {
            file.path(path.expand("~"), ".local", "bin")
        }
    }
    bin_dir <- path.expand(bin_dir)
    bin_dir <- normalizePath(bin_dir, mustWork = dir.exists(bin_dir), winslash = "/")
    command <- name
    file_name <- name
    if (isTRUE(windows) && !grepl("[.]cmd$", file_name, ignore.case = TRUE)) {
        file_name <- paste0(file_name, ".cmd")
        command <- file_name
    }
    list(
        windows = windows,
        bin_dir = bin_dir,
        command = command,
        path = file.path(bin_dir, file_name)
    )
}

epwshiftr_cli_launcher_content <- function(windows = .Platform$OS.type == "windows") {
    rscript <- file.path(R.home("bin"), if (isTRUE(windows)) "Rscript.exe" else "Rscript")
    rscript <- normalizePath(rscript, mustWork = FALSE, winslash = if (isTRUE(windows)) "\\" else "/")
    expr <- "epwshiftr::epwshiftr_cli(exit = TRUE)"
    if (isTRUE(windows)) {
        return(c(
            "@echo off",
            "rem Generated by epwshiftr::install_cli()",
            sprintf("\"%s\" --vanilla -e \"%s\" %%*", rscript, expr)
        ))
    }
    c(
        "#!/bin/sh",
        "# Generated by epwshiftr::install_cli()",
        sprintf("exec %s --vanilla -e %s \"$@\"", shQuote(rscript), shQuote(expr))
    )
}

epwshiftr_cli_bin_in_path <- function(bin_dir) {
    path <- Sys.getenv("PATH", unset = "")
    if (!nzchar(path)) {
        return(FALSE)
    }
    dirs <- strsplit(path, .Platform$path.sep, fixed = TRUE)[[1L]]
    dirs <- dirs[nzchar(dirs)]
    if (!length(dirs)) {
        return(FALSE)
    }
    normalized <- vapply(dirs, normalizePath, character(1L), mustWork = FALSE, winslash = "/")
    normalizePath(bin_dir, mustWork = FALSE, winslash = "/") %in% normalized
}
