#' Run the epwshiftr command line interface
#'
#' @description
#' `epwshiftr_cli()` is the package-level entry point used by the optional
#' `epwshiftr` launcher. It exposes a small ESGF store workflow interface and
#' returns status metadata when `exit = FALSE`, which makes it testable from R.
#'
#' @param args Command line arguments. Defaults to
#'        `commandArgs(trailingOnly = TRUE)`.
#' @param exit Whether to terminate the current R process with the command
#'        status. Default: `FALSE`.
#'
#' @return Invisibly, a list with `status`, `result`, and `error`.
#' @export
epwshiftr_cli <- function(args = commandArgs(trailingOnly = TRUE), exit = FALSE) {
    checkmate::assert_character(args, any.missing = FALSE)
    checkmate::assert_flag(exit)

    parsed <- NULL
    status <- 0L
    result <- NULL
    error <- NULL
    tryCatch(
        {
            parsed <- epwshiftr_cli_parse_globals(args)
            result <- epwshiftr_cli_dispatch(parsed)
            epwshiftr_cli_emit_result(result, json = parsed$json, quiet = parsed$quiet)
        },
        epwshiftr_cli_usage_error = function(e) {
            status <<- 2L
            error <<- conditionMessage(e)
            epwshiftr_cli_emit_error(error, json = epwshiftr_cli_has_flag(args, "--json"), quiet = epwshiftr_cli_has_flag(args, "--quiet"), status = status)
        },
        error = function(e) {
            status <<- 1L
            error <<- conditionMessage(e)
            epwshiftr_cli_emit_error(error, json = epwshiftr_cli_has_flag(args, "--json"), quiet = epwshiftr_cli_has_flag(args, "--quiet"), status = status)
        }
    )
    out <- list(status = status, result = result, error = error)
    if (isTRUE(exit)) {
        quit(status = status, save = "no")
    }
    invisible(out)
}

#' Install the epwshiftr command launcher
#'
#' @description
#' `install_cli()` writes a small platform launcher that runs the current
#' `Rscript` with `epwshiftr::epwshiftr_cli(exit = TRUE)`. It does not modify
#' shell profiles or `PATH`.
#'
#' @param bin_dir Directory where the launcher should be written. Defaults to
#'        `~/.local/bin` on macOS/Linux and
#'        `%LOCALAPPDATA%/epwshiftr/bin` on Windows.
#' @param name Launcher command name. Default: `"epwshiftr"`.
#' @param overwrite Whether to replace an existing launcher. Default: `FALSE`.
#'
#' @return A data.table describing the installed launcher.
#' @export
install_cli <- function(bin_dir = NULL, name = "epwshiftr", overwrite = FALSE) {
    checkmate::assert_string(bin_dir, min.chars = 1L, null.ok = TRUE)
    checkmate::assert_string(name, min.chars = 1L)
    checkmate::assert_flag(overwrite)
    if (!grepl("^[A-Za-z][A-Za-z0-9._-]*$", name)) {
        cli::cli_abort("{.arg name} must start with a letter and contain only letters, digits, '.', '_', or '-'.")
    }

    spec <- epwshiftr_cli_launcher_spec(bin_dir, name)
    if (file.exists(spec$path) && !isTRUE(overwrite)) {
        cli::cli_abort("Launcher already exists at {.path {spec$path}}. Use {.code overwrite = TRUE} to replace it.")
    }
    if (!dir.exists(spec$bin_dir)) {
        dir.create(spec$bin_dir, recursive = TRUE, showWarnings = FALSE)
    }
    if (!dir.exists(spec$bin_dir)) {
        cli::cli_abort("Failed to create launcher directory: {.path {spec$bin_dir}}.")
    }
    spec$bin_dir <- normalizePath(spec$bin_dir, mustWork = TRUE, winslash = "/")
    spec$path <- file.path(spec$bin_dir, basename(spec$path))

    writeLines(epwshiftr_cli_launcher_content(spec$windows), spec$path, useBytes = TRUE)
    if (!isTRUE(spec$windows)) {
        Sys.chmod(spec$path, mode = "0755")
    }
    in_path <- epwshiftr_cli_bin_in_path(spec$bin_dir)
    if (!isTRUE(in_path)) {
        cli::cli_inform("Launcher installed at {.path {spec$path}}, but {.path {spec$bin_dir}} is not currently on PATH.")
    }
    data.table::data.table(
        path = spec$path,
        bin_dir = spec$bin_dir,
        command = spec$command,
        in_path = in_path,
        installed = TRUE
    )
}

#' Uninstall the epwshiftr command launcher
#'
#' @description
#' Remove a launcher generated by `install_cli()`.
#'
#' @inheritParams install_cli
#'
#' @return A data.table describing the uninstall result.
#' @export
uninstall_cli <- function(bin_dir = NULL, name = "epwshiftr") {
    checkmate::assert_string(bin_dir, min.chars = 1L, null.ok = TRUE)
    checkmate::assert_string(name, min.chars = 1L)
    spec <- epwshiftr_cli_launcher_spec(bin_dir, name)
    if (!file.exists(spec$path)) {
        return(data.table::data.table(
            path = spec$path,
            bin_dir = spec$bin_dir,
            command = spec$command,
            removed = FALSE,
            message = "launcher not found"
        ))
    }
    content <- readLines(spec$path, warn = FALSE)
    if (!any(grepl("Generated by epwshiftr::install_cli\\(\\)", content)) ||
        !any(grepl("epwshiftr::epwshiftr_cli\\(exit = TRUE\\)", content, fixed = FALSE))) {
        cli::cli_abort("Refusing to remove {.path {spec$path}} because it was not generated by {.fn epwshiftr::install_cli}.")
    }
    removed <- unlink(spec$path, recursive = FALSE, force = TRUE) == 0L
    data.table::data.table(
        path = spec$path,
        bin_dir = spec$bin_dir,
        command = spec$command,
        removed = removed,
        message = if (isTRUE(removed)) "removed launcher" else "failed to remove launcher"
    )
}

epwshiftr_cli_parse_globals <- function(args) {
    out <- list(
        store = NULL,
        json = FALSE,
        quiet = FALSE,
        help = FALSE,
        args = character()
    )
    i <- 1L
    while (i <= length(args)) {
        arg <- args[[i]]
        if (identical(arg, "--store")) {
            if (i == length(args)) {
                epwshiftr_cli_usage_abort("--store requires a path.")
            }
            out$store <- args[[i + 1L]]
            i <- i + 2L
            next
        }
        if (startsWith(arg, "--store=")) {
            out$store <- sub("^--store=", "", arg)
            if (!nzchar(out$store)) {
                epwshiftr_cli_usage_abort("--store requires a path.")
            }
            i <- i + 1L
            next
        }
        if (identical(arg, "--json")) {
            out$json <- TRUE
            i <- i + 1L
            next
        }
        if (identical(arg, "--quiet")) {
            out$quiet <- TRUE
            i <- i + 1L
            next
        }
        if (arg %in% c("--help", "-h")) {
            out$help <- TRUE
            i <- i + 1L
            next
        }
        out$args <- c(out$args, arg)
        i <- i + 1L
    }
    out
}

epwshiftr_cli_dispatch <- function(parsed) {
    if (isTRUE(parsed$help)) {
        return(epwshiftr_cli_usage())
    }
    args <- parsed$args
    if (length(args) < 2L) {
        epwshiftr_cli_usage_abort(epwshiftr_cli_usage())
    }

    store <- EsgStore$new(path = parsed$store)
    on.exit(store$close(), add = TRUE)

    group <- args[[1L]]
    command <- args[[2L]]
    rest <- args[-seq_len(2L)]

    if (identical(group, "query")) {
        return(epwshiftr_cli_query(store, command, rest))
    }
    if (identical(group, "download")) {
        return(epwshiftr_cli_download(store, command, rest))
    }
    if (identical(group, "workflow")) {
        return(epwshiftr_cli_workflow(store, command, rest))
    }
    if (identical(group, "storage")) {
        return(epwshiftr_cli_storage(store, command, rest))
    }
    epwshiftr_cli_usage_abort(sprintf("Unknown command group: %s", group))
}

epwshiftr_cli_query <- function(store, command, args) {
    if (identical(command, "list")) {
        parsed <- epwshiftr_cli_parse_command(args)
        epwshiftr_cli_assert_no_positionals(parsed)
        return(store$queries())
    }
    if (identical(command, "show")) {
        parsed <- epwshiftr_cli_parse_command(args, flags = c("--files", "--updates", "--changes"))
        query_id <- epwshiftr_cli_required_position(parsed, "query_id")
        query <- store$queries()
        query <- query[query[["query_id"]] == query_id]
        if (!nrow(query)) {
            cli::cli_abort("Unknown query ID: {.val {query_id}}.")
        }
        out <- list(
            query = query[],
            tags = store$query_tags(query_id),
            graph = store$query_graph(query_id = query_id, direction = "both"),
            status = store$query_status(query_id)
        )
        if (isTRUE(parsed$flags[["--files"]])) {
            out$files <- store$query_files(query_id)
        }
        if (isTRUE(parsed$flags[["--updates"]])) {
            out$updates <- store$query_updates(query_id)
        }
        if (isTRUE(parsed$flags[["--changes"]])) {
            updates <- store$query_updates(query_id, latest = TRUE)
            out$changes <- if (nrow(updates)) {
                store$query_changes(update_id = updates$update_id)
            } else {
                data.table::data.table()
            }
        }
        return(out)
    }
    if (identical(command, "status")) {
        parsed <- epwshiftr_cli_parse_command(args)
        query_id <- epwshiftr_cli_optional_position(parsed, "query_id")
        return(store$query_status(query_id))
    }
    if (identical(command, "files")) {
        parsed <- epwshiftr_cli_parse_command(args, options = "--status")
        query_id <- epwshiftr_cli_required_position(parsed, "query_id")
        return(store$query_files(query_id, status = epwshiftr_cli_csv(parsed$options[["--status"]])))
    }
    if (identical(command, "updates")) {
        parsed <- epwshiftr_cli_parse_command(args, flags = "--latest")
        query_id <- epwshiftr_cli_optional_position(parsed, "query_id")
        return(store$query_updates(query_id = query_id, latest = parsed$flags[["--latest"]]))
    }
    if (identical(command, "changes")) {
        parsed <- epwshiftr_cli_parse_command(args, flags = "--latest", options = c("--update", "--type"))
        query_id <- epwshiftr_cli_optional_position(parsed, "query_id")
        update_id <- parsed$options[["--update"]]
        if (is.null(update_id) && isTRUE(parsed$flags[["--latest"]])) {
            updates <- store$query_updates(query_id = query_id, latest = TRUE)
            if (!nrow(updates)) {
                return(data.table::data.table())
            }
            update_id <- if (nrow(updates)) updates$update_id else character()
        }
        return(store$query_changes(
            update_id = epwshiftr_cli_empty_to_null(update_id),
            query_id = query_id,
            change_type = epwshiftr_cli_csv(parsed$options[["--type"]])
        ))
    }
    if (identical(command, "tags")) {
        parsed <- epwshiftr_cli_parse_command(args)
        query_id <- epwshiftr_cli_optional_position(parsed, "query_id")
        return(store$query_tags(query_id))
    }
    if (identical(command, "track")) {
        parsed <- epwshiftr_cli_parse_command(args)
        query_id <- epwshiftr_cli_required_position(parsed, "query_id")
        store$track_query(query_id)
        return(epwshiftr_cli_query_row(store, query_id))
    }
    if (identical(command, "untrack")) {
        parsed <- epwshiftr_cli_parse_command(args)
        query_id <- epwshiftr_cli_required_position(parsed, "query_id")
        store$untrack_query(query_id)
        return(epwshiftr_cli_query_row(store, query_id))
    }
    if (identical(command, "tag")) {
        parsed <- epwshiftr_cli_parse_command(args, flags = "--replace")
        if (length(parsed$positionals) < 2L) {
            epwshiftr_cli_usage_abort("Missing required arguments: query_id and tag.")
        }
        query_id <- parsed$positionals[[1L]]
        tags <- parsed$positionals[-1L]
        return(store$tag_query(query_id, tags, replace = parsed$flags[["--replace"]]))
    }
    if (identical(command, "untag")) {
        parsed <- epwshiftr_cli_parse_command(args)
        if (!length(parsed$positionals)) {
            epwshiftr_cli_usage_abort("Missing required argument: query_id.")
        }
        query_id <- parsed$positionals[[1L]]
        tags <- if (length(parsed$positionals) > 1L) parsed$positionals[-1L] else NULL
        return(store$untag_query(query_id, tags))
    }
    if (identical(command, "remove")) {
        parsed <- epwshiftr_cli_parse_command(args, flags = "--execute", options = "--delete")
        query_id <- epwshiftr_cli_required_position(parsed, "query_id")
        delete <- parsed$options[["--delete"]]
        if (is.null(delete)) {
            delete <- "none"
        }
        if (!delete %in% c("none", "orphaned")) {
            epwshiftr_cli_usage_abort("--delete must be one of: none, orphaned.")
        }
        if (isTRUE(parsed$flags[["--execute"]])) {
            return(store$remove_query(query_id, delete = delete))
        }
        return(epwshiftr_cli_query_remove_preview(store, query_id, delete))
    }
    if (identical(command, "preview")) {
        parsed <- epwshiftr_cli_parse_command(args, flags = "--detail")
        query_id <- epwshiftr_cli_optional_position(parsed, "query_id")
        return(store$preview_update_queries(query_id = query_id, detail = parsed$flags[["--detail"]]))
    }
    if (identical(command, "update")) {
        parsed <- epwshiftr_cli_parse_command(args)
        query_id <- epwshiftr_cli_optional_position(parsed, "query_id")
        return(store$update_queries(query_id = query_id))
    }
    epwshiftr_cli_usage_abort(sprintf("Unknown query command: %s", command))
}

epwshiftr_cli_download <- function(store, command, args) {
    if (identical(command, "preflight")) {
        parsed <- epwshiftr_cli_parse_command(args)
        query_id <- epwshiftr_cli_required_position(parsed, "query_id")
        return(store$download_preflight(query_id))
    }
    if (identical(command, "run")) {
        parsed <- epwshiftr_cli_parse_command(args)
        query_id <- epwshiftr_cli_required_position(parsed, "query_id")
        return(store$download_query(query_id))
    }
    if (identical(command, "status")) {
        parsed <- epwshiftr_cli_parse_command(args, options = c("--query", "--session"))
        epwshiftr_cli_assert_no_positionals(parsed)
        return(store$download_status(
            query_id = parsed$options[["--query"]],
            session_id = parsed$options[["--session"]]
        ))
    }
    if (identical(command, "retry")) {
        parsed <- epwshiftr_cli_parse_command(args, flags = "--run", options = c("--query", "--session"))
        epwshiftr_cli_assert_no_positionals(parsed)
        return(store$retry_downloads(
            query_id = parsed$options[["--query"]],
            session_id = parsed$options[["--session"]],
            run = parsed$flags[["--run"]]
        ))
    }
    epwshiftr_cli_usage_abort(sprintf("Unknown download command: %s", command))
}

epwshiftr_cli_workflow <- function(store, command, args) {
    if (identical(command, "report")) {
        parsed <- epwshiftr_cli_parse_command(args, options = "--query")
        epwshiftr_cli_assert_no_positionals(parsed)
        return(store$workflow_report(query_id = parsed$options[["--query"]]))
    }
    epwshiftr_cli_usage_abort(sprintf("Unknown workflow command: %s", command))
}

epwshiftr_cli_storage <- function(store, command, args) {
    if (identical(command, "report")) {
        parsed <- epwshiftr_cli_parse_command(args, flags = "--detail")
        epwshiftr_cli_assert_no_positionals(parsed)
        return(store$storage_report(detail = parsed$flags[["--detail"]]))
    }
    if (identical(command, "validate")) {
        parsed <- epwshiftr_cli_parse_command(args, flags = "--checksum")
        epwshiftr_cli_assert_no_positionals(parsed)
        return(store$validate_files(checksum = parsed$flags[["--checksum"]]))
    }
    if (identical(command, "repair")) {
        parsed <- epwshiftr_cli_parse_command(args, flags = "--execute")
        epwshiftr_cli_assert_no_positionals(parsed)
        return(store$repair_files(dry_run = !parsed$flags[["--execute"]]))
    }
    epwshiftr_cli_usage_abort(sprintf("Unknown storage command: %s", command))
}

epwshiftr_cli_parse_command <- function(args, flags = character(), options = character()) {
    flag_values <- stats::setNames(rep(FALSE, length(flags)), flags)
    option_values <- stats::setNames(rep(list(NULL), length(options)), options)
    positionals <- character()
    i <- 1L
    while (i <= length(args)) {
        arg <- args[[i]]
        if (arg %in% flags) {
            flag_values[[arg]] <- TRUE
            i <- i + 1L
            next
        }
        option_match <- options[startsWith(arg, paste0(options, "="))]
        if (length(option_match)) {
            option <- option_match[[1L]]
            option_values[[option]] <- sub(sprintf("^%s=", option), "", arg)
            if (!nzchar(option_values[[option]])) {
                epwshiftr_cli_usage_abort(sprintf("%s requires a value.", option))
            }
            i <- i + 1L
            next
        }
        if (arg %in% options) {
            if (i == length(args)) {
                epwshiftr_cli_usage_abort(sprintf("%s requires a value.", arg))
            }
            option_values[[arg]] <- args[[i + 1L]]
            i <- i + 2L
            next
        }
        if (startsWith(arg, "--")) {
            epwshiftr_cli_usage_abort(sprintf("Unknown option: %s", arg))
        }
        positionals <- c(positionals, arg)
        i <- i + 1L
    }
    list(positionals = positionals, flags = flag_values, options = option_values)
}

epwshiftr_cli_optional_position <- function(parsed, name) {
    if (length(parsed$positionals) > 1L) {
        epwshiftr_cli_usage_abort(sprintf("Too many positional arguments for %s.", name))
    }
    if (!length(parsed$positionals)) {
        return(NULL)
    }
    parsed$positionals[[1L]]
}

epwshiftr_cli_required_position <- function(parsed, name) {
    if (!length(parsed$positionals)) {
        epwshiftr_cli_usage_abort(sprintf("Missing required argument: %s", name))
    }
    if (length(parsed$positionals) > 1L) {
        epwshiftr_cli_usage_abort(sprintf("Too many positional arguments for %s.", name))
    }
    parsed$positionals[[1L]]
}

epwshiftr_cli_assert_no_positionals <- function(parsed) {
    if (length(parsed$positionals)) {
        epwshiftr_cli_usage_abort(sprintf("Unexpected argument: %s", parsed$positionals[[1L]]))
    }
    invisible(NULL)
}

epwshiftr_cli_csv <- function(value) {
    if (is.null(value) || !length(value)) {
        return(NULL)
    }
    value <- unlist(strsplit(value, ",", fixed = TRUE), use.names = FALSE)
    value <- trimws(value)
    value <- value[nzchar(value)]
    if (!length(value)) {
        return(NULL)
    }
    unique(value)
}

epwshiftr_cli_empty_to_null <- function(value) {
    if (is.null(value) || !length(value)) {
        return(NULL)
    }
    value
}

epwshiftr_cli_query_remove_preview <- function(store, query_id, delete = "none") {
    query <- epwshiftr_cli_query_row(store, query_id)
    files <- store$query_files(query_id)
    data.table::data.table(
        dry_run = TRUE,
        query_id = query_id,
        delete = delete,
        file_count = as.integer(nrow(files)),
        tag_count = as.integer(nrow(store$query_tags(query_id))),
        dependency_count = as.integer(nrow(store$query_graph(query_id = query_id, direction = "both"))),
        execute_hint = "rerun with --execute to remove the query"
    )
}

epwshiftr_cli_query_row <- function(store, query_id) {
    query <- store$queries()
    query <- query[query[["query_id"]] == query_id]
    if (!nrow(query)) {
        cli::cli_abort("Unknown query ID: {.val {query_id}}.")
    }
    query[]
}

epwshiftr_cli_emit_result <- function(result, json = FALSE, quiet = FALSE) {
    if (isTRUE(quiet)) {
        return(invisible(NULL))
    }
    if (isTRUE(json)) {
        cat(jsonlite::toJSON(result, dataframe = "rows", POSIXt = "ISO8601", auto_unbox = TRUE, null = "null", pretty = TRUE))
        cat("\n")
        return(invisible(NULL))
    }
    if (is.character(result)) {
        cli::cli_text(paste(result, collapse = "\n"))
    } else {
        print(result)
    }
    invisible(NULL)
}

epwshiftr_cli_emit_error <- function(message, json = FALSE, quiet = FALSE, status = 1L) {
    if (isTRUE(quiet)) {
        return(invisible(NULL))
    }
    if (isTRUE(json)) {
        cat(jsonlite::toJSON(list(status = status, error = message), auto_unbox = TRUE, null = "null", pretty = TRUE))
        cat("\n")
        return(invisible(NULL))
    }
    cli::cli_alert_danger(message)
    invisible(NULL)
}

epwshiftr_cli_usage <- function() {
    c(
        "Usage: epwshiftr [--store PATH] [--json] [--quiet] <group> <command> [options]",
        "",
        "Commands:",
        "  epwshiftr query list",
        "  epwshiftr query show <query_id> [--files] [--updates] [--changes]",
        "  epwshiftr query status [query_id]",
        "  epwshiftr query files <query_id> [--status STATUS]",
        "  epwshiftr query updates [query_id] [--latest]",
        "  epwshiftr query changes [query_id] [--latest] [--update UPDATE_ID] [--type TYPE]",
        "  epwshiftr query tags [query_id]",
        "  epwshiftr query track <query_id>",
        "  epwshiftr query untrack <query_id>",
        "  epwshiftr query tag <query_id> <tag>... [--replace]",
        "  epwshiftr query untag <query_id> [tag...]",
        "  epwshiftr query remove <query_id> [--delete none|orphaned] [--execute]",
        "  epwshiftr query preview [query_id] [--detail]",
        "  epwshiftr query update [query_id]",
        "  epwshiftr download preflight <query_id>",
        "  epwshiftr download run <query_id>",
        "  epwshiftr download status [--query QUERY_ID] [--session SESSION_ID]",
        "  epwshiftr download retry [--query QUERY_ID] [--session SESSION_ID] [--run]",
        "  epwshiftr workflow report [--query QUERY_ID]",
        "  epwshiftr storage report [--detail]",
        "  epwshiftr storage validate [--checksum]",
        "  epwshiftr storage repair [--execute]"
    )
}

epwshiftr_cli_usage_abort <- function(message) {
    stop(structure(
        list(message = paste(message, collapse = "\n"), call = NULL),
        class = c("epwshiftr_cli_usage_error", "error", "condition")
    ))
}

epwshiftr_cli_has_flag <- function(args, flag) {
    any(args %in% flag)
}

epwshiftr_cli_launcher_spec <- function(bin_dir = NULL, name = "epwshiftr") {
    windows <- .Platform$OS.type == "windows"
    if (is.null(bin_dir)) {
        bin_dir <- if (isTRUE(windows)) {
            local_app <- Sys.getenv("LOCALAPPDATA", unset = NA_character_)
            if (is.na(local_app) || !nzchar(local_app)) {
                local_app <- file.path(path.expand("~"), "AppData", "Local")
            }
            file.path(local_app, "epwshiftr", "bin")
        } else {
            file.path(path.expand("~"), ".local", "bin")
        }
    }
    bin_dir <- path.expand(bin_dir)
    bin_dir <- normalizePath(bin_dir, mustWork = dir.exists(bin_dir), winslash = "/")
    command <- name
    file_name <- name
    if (isTRUE(windows) && !grepl("[.]cmd$", file_name, ignore.case = TRUE)) {
        file_name <- paste0(file_name, ".cmd")
        command <- file_name
    }
    list(
        windows = windows,
        bin_dir = bin_dir,
        command = command,
        path = file.path(bin_dir, file_name)
    )
}

epwshiftr_cli_launcher_content <- function(windows = .Platform$OS.type == "windows") {
    rscript <- file.path(R.home("bin"), if (isTRUE(windows)) "Rscript.exe" else "Rscript")
    rscript <- normalizePath(rscript, mustWork = FALSE, winslash = if (isTRUE(windows)) "\\" else "/")
    expr <- "epwshiftr::epwshiftr_cli(exit = TRUE)"
    if (isTRUE(windows)) {
        return(c(
            "@echo off",
            "rem Generated by epwshiftr::install_cli()",
            sprintf("\"%s\" --vanilla -e \"%s\" %%*", rscript, expr)
        ))
    }
    c(
        "#!/bin/sh",
        "# Generated by epwshiftr::install_cli()",
        sprintf("exec %s --vanilla -e %s \"$@\"", shQuote(rscript), shQuote(expr))
    )
}

epwshiftr_cli_bin_in_path <- function(bin_dir) {
    path <- Sys.getenv("PATH", unset = "")
    if (!nzchar(path)) {
        return(FALSE)
    }
    dirs <- strsplit(path, .Platform$path.sep, fixed = TRUE)[[1L]]
    dirs <- dirs[nzchar(dirs)]
    if (!length(dirs)) {
        return(FALSE)
    }
    normalized <- vapply(dirs, normalizePath, character(1L), mustWork = FALSE, winslash = "/")
    normalizePath(bin_dir, mustWork = FALSE, winslash = "/") %in% normalized
}
